version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://172.30.1.88:3306/train_booking?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: tuser
      SPRING_DATASOURCE_PASSWORD: t123456
    depends_on:
      - db
    restart: on-failure